version: '2.0'

services:
  spring-boot-modular:
    container_name: "spring-boot-modular"
    build: '.'
    restart: unless-stopped
    ports:
      - "8443:443"
      - "8080:80"
    environment:
      DATABASE_URL: 'jdbc:mysql://spring-boot-modular-db:3306/prod_db'
      DATABASE_SCHEMA: 'prod_db'
      DATABASE_ADMIN_USER: 'root'
      DATABASE_ADMIN_PASSWORD: 'root-secret'
      DATABASE_USER: 'prod-user'
      DATABASE_PASSWORD: 'prod-secret'
    depends_on:
      - mysql
    volumes:
      - ./docker/config:/config:ro
      - ./docker/logs:/opt/app/logs
    networks:
      - front-tier
      - back-tier
    mem_reservation: 50m
    mem_limit: 200m

  mysql:
    container_name: spring-boot-modular-db
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root-secret'
      MYSQL_DATABASE: 'prod_db'
      MYSQL_USER: 'prod-user'
      MYSQL_PASSWORD: 'prod-secret'
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - front-tier
      - back-tier
    mem_reservation: 50m
    mem_limit: 200m

    
networks:
  front-tier:
  back-tier:
    driver: bridge
