version: '2.0'

services:
  spring-boot-modular:
    container_name: "spring-boot-modular"
    build: '.'
    restart: unless-stopped
    ports:
      - "8443:443"
    environment:
      DATABASE_URL: 'jdbc:mysql://spring-boot-modular-db:3306/prod_db'
      DATABASE_SCHEMA: 'prod_db'
      DATABASE_ADMIN_USER: 'root'
      DATABASE_ADMIN_PASSWORD: 'root-secret'
      DATABASE_USER: 'prod-user'
      DATABASE_PASSWORD: 'prod-secret'
    depends_on:
      - mysql
    volumes:
      - ./docker/config/spring:/config:ro
      - ./docker/data/logs:/opt/app/logs
    networks:
      - front-tier
      - back-tier
    mem_reservation: 128m
    mem_limit: 256m

  mysql:
    container_name: spring-boot-modular-db
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root-secret'
      MYSQL_DATABASE: 'prod_db'
      MYSQL_USER: 'prod-user'
      MYSQL_PASSWORD: 'prod-secret'
    volumes:
      - mysql-storage:/var/lib/mysql:rw
    networks:
      - front-tier
      - back-tier
    mem_reservation: 50m
    mem_limit: 512m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    networks:
      - front-tier
      - back-tier
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - front-tier
      - back-tier
    depends_on:
      - prometheus
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./docker/config/grafana/:/etc/grafana/provisioning/

networks:
  front-tier:
  back-tier:
    driver: bridge

volumes:
  grafana-storage:
  mysql-storage:
