version: '3.0'
services:
  spring-boot-modular:
    container_name: "spring-boot-modular"
    build: '.'
    restart: always
    ports:
      - "8443:443"
      - "8080:80"
    environment:
      DATABASE_URL: 'jdbc:mysql://spring-boot-modular-db:3306/prod_db'
      DATABASE_SCHEMA: 'prod_db'
      DATABASE_ADMIN_USER: 'root'
      DATABASE_ADMIN_PASSWORD: 'root-secret'
      DATABASE_USER: 'prod-user'
      DATABASE_PASSWORD: 'prod-secret'
    depends_on:
      - mysql
    volumes:
      - ./docker/config:/config:ro
  mysql:
    container_name: spring-boot-modular-db
    restart: always
    image: mysql:latest
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root-secret'
      MYSQL_DATABASE: 'prod_db'
      MYSQL_USER: 'prod-user'
      MYSQL_PASSWORD: 'prod-secret'
    volumes:
      - ./docker/database:/var/lib/mysql
