{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.frostnova.spring-multimodule",
    "module": "platform",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "n4z72cqnfveqdhx5a4f2spvqua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.frostnova.spring-multimodule",
          "module": "platform",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-3.jar",
          "size": 2385,
          "sha512": "cfcb2f074800789f96ef52c15ed29d4a3348fdb1373b3d2227a8333985bfc735a83cd5dcda30ec57b857fbe04bd508934906cb05fc1a92bef49cd7262f6d9516",
          "sha256": "94bf4cf20bbcd335fc1d407fb82120552d8cf51b92446b116043659d7fee24e6",
          "sha1": "0c5145d2e3b53426b9a51c5ed158fc57a8584660",
          "md5": "9b88b4e0c3714ff642c635327e3b7e4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "ch.frostnova.spring-multimodule",
          "module": "platform",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-3.jar",
          "size": 2385,
          "sha512": "cfcb2f074800789f96ef52c15ed29d4a3348fdb1373b3d2227a8333985bfc735a83cd5dcda30ec57b857fbe04bd508934906cb05fc1a92bef49cd7262f6d9516",
          "sha256": "94bf4cf20bbcd335fc1d407fb82120552d8cf51b92446b116043659d7fee24e6",
          "sha1": "0c5145d2e3b53426b9a51c5ed158fc57a8584660",
          "md5": "9b88b4e0c3714ff642c635327e3b7e4b"
        }
      ]
    }
  ]
}
