{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.frostnova.spring-multimodule",
    "module": "platform",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "n4z72cqnfveqdhx5a4f2spvqua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.19"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-5.jar",
          "size": 16281,
          "sha512": "50e82e2eb87e8b166ec6c68a9b5b6ddebfba6780ee140e96aea57e1cb7d8c70a0e52dc519ee53a61e7da5452f57ba20dc761892abe811813febc66ae16a1b242",
          "sha256": "909891d7672c13f8c43a0b014dcaabd394ad6af9027e617d80ef6e610b25c97e",
          "sha1": "d8c96f0a70189c5374b574001023fb6d8e724c4b",
          "md5": "07ab4438b9108d87f65e23d9a1c453e8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.19"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-5.jar",
          "size": 16281,
          "sha512": "50e82e2eb87e8b166ec6c68a9b5b6ddebfba6780ee140e96aea57e1cb7d8c70a0e52dc519ee53a61e7da5452f57ba20dc761892abe811813febc66ae16a1b242",
          "sha256": "909891d7672c13f8c43a0b014dcaabd394ad6af9027e617d80ef6e610b25c97e",
          "sha1": "d8c96f0a70189c5374b574001023fb6d8e724c4b",
          "md5": "07ab4438b9108d87f65e23d9a1c453e8"
        }
      ]
    }
  ]
}
