{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.frostnova.spring-multimodule",
    "module": "platform",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "n4z72cqnfveqdhx5a4f2spvqua"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "ch.frostnova.spring-multimodule",
          "module": "platform",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-6.jar",
          "size": 13093,
          "sha512": "9a7b8a27d91406a583505920644ee00c5837453e4d6528007afddcbd78a33b3605333b9568d90ac73946f3f0354b629921a55a81bfb7c623fb4879a9752c7e57",
          "sha256": "19a76b5e67d4c7e5bc064f45cb6e92ca1e5e82caddc08942f1899ae89aec8a09",
          "sha1": "f87091809ee61914af3aecbf11e0081e5ec7211e",
          "md5": "890dcdf21c7bf4e80759d3bb830498f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 13,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "ch.frostnova.spring-multimodule",
          "module": "platform",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.19"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "ch.frostnova.spring-multimodule",
          "module": "platform",
          "version": {
            "requires": "1.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-6.jar",
          "size": 13093,
          "sha512": "9a7b8a27d91406a583505920644ee00c5837453e4d6528007afddcbd78a33b3605333b9568d90ac73946f3f0354b629921a55a81bfb7c623fb4879a9752c7e57",
          "sha256": "19a76b5e67d4c7e5bc064f45cb6e92ca1e5e82caddc08942f1899ae89aec8a09",
          "sha1": "f87091809ee61914af3aecbf11e0081e5ec7211e",
          "md5": "890dcdf21c7bf4e80759d3bb830498f7"
        }
      ]
    }
  ]
}
version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.19"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "3.8.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "snakeyaml"
            }
          ]
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200203.231449-6.jar",
          "size": 65141,
          "sha512": "e589648214f02e27f18e13df7ecbdb8b118d8936e82b95b2287f4191e958c4093bf359080ecfb7efb44dd53a8713c43795cffc2de37ede7ae1eebf3820b885aa",
          "sha256": "e0bbb3c92f6be2ec47c604926b0522dd6c66d8a62f367e47319417f10c778667",
          "sha1": "497bd43266663021bf0c37296cd1de0bd9cc75fb",
          "md5": "19cd64b766761cf3594bb6c5c74ce99c"
        }
      ]
    }
  ]
}
