{
  "formatVersion": "1.1",
  "component": {
    "group": "ch.frostnova.spring-multimodule",
    "module": "platform",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "3ezcd253yjaefjzleisjdcl7qm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.19"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "3.8.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "snakeyaml"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200204.223022-1.jar",
          "size": 65141,
          "sha512": "0e6f5a9e2851c01fbc86a5912f2e478a39e1b8c48920c1cea8b75bc4084f7d565311a3466f5fc99c097be06d6507fa90d2a4c78e2ef48c86c03f8df8ca3a8cf9",
          "sha256": "5ee5869056df2d79933b9a347af49f0252637fea06e5ad793d8570ad1ee1f380",
          "sha1": "b5bef97e75a46bdae3835878cf76f198209b9cff",
          "md5": "3e5241eb94bb6009ef1e265656f49259"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.10.2"
          }
        },
        {
          "group": "javax.validation",
          "module": "validation-api",
          "version": {
            "requires": "2.0.1.Final"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger2",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-web",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-security",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-cache",
          "version": {
            "requires": "2.2.4.RELEASE"
          }
        },
        {
          "group": "net.logstash.logback",
          "module": "logstash-logback-encoder",
          "version": {
            "requires": "6.3"
          }
        },
        {
          "group": "org.codehaus.janino",
          "module": "janino",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "io.micrometer",
          "module": "micrometer-registry-prometheus",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "io.springfox",
          "module": "springfox-swagger-ui",
          "version": {
            "requires": "2.9.2"
          }
        },
        {
          "group": "mysql",
          "module": "mysql-connector-java",
          "version": {
            "requires": "8.0.19"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "1.4.200"
          }
        },
        {
          "group": "javax.cache",
          "module": "cache-api",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.ehcache",
          "module": "ehcache",
          "version": {
            "requires": "3.8.1"
          }
        },
        {
          "group": "io.jsonwebtoken",
          "module": "jjwt",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.liquibase",
          "module": "liquibase-core",
          "version": {
            "requires": "3.8.5"
          },
          "excludes": [
            {
              "group": "*",
              "module": "snakeyaml"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "platform-1.0.0-SNAPSHOT.jar",
          "url": "platform-1.0.0-20200204.223022-1.jar",
          "size": 65141,
          "sha512": "0e6f5a9e2851c01fbc86a5912f2e478a39e1b8c48920c1cea8b75bc4084f7d565311a3466f5fc99c097be06d6507fa90d2a4c78e2ef48c86c03f8df8ca3a8cf9",
          "sha256": "5ee5869056df2d79933b9a347af49f0252637fea06e5ad793d8570ad1ee1f380",
          "sha1": "b5bef97e75a46bdae3835878cf76f198209b9cff",
          "md5": "3e5241eb94bb6009ef1e265656f49259"
        }
      ]
    }
  ]
}
