info:
  app:
    name: "spring-multi-module"
    description: "Spring Boot Multi Module Project"
    version: "1.0.0-SNAPSHOT"

spring.profiles.active: performance-logging

# TLS configuration - enable HTTPS
server:
  port: 8443
  ssl:
    enabled: true
    protocol: TLSv1.2
    enabled-protocols: TLSv1.1+TLSv1.2
    ciphers: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_DHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_DHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256
    key-alias: "test-server"
    key-store: "classpath:server-keystore.jks"
    key-store-password: "keystore"
    key-password: "keystore"

# HTTP port for redirection to HTTPS - uncomment to activate
# http.server.port: 80

# Persistence: datasource/JPA configuration
spring:
  datasource:
    url: jdbc:h2:file:./db/h2-database
    username: test
    password: test
    driver-class-name: org.h2.Driver
    tomcat:
      removeAbandoned: true
      removeAbandonedTimeout: 120
      logAbandoned: true
      maxActive: 50
      maxIdle: 5
      maxWait: 1000
      validationQuery: "select 1"
      testOnBorrow: true
      testOnConnect: true
      testWhileIdle: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: TEST
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    parameters:
      schema: TEST

# Actuator configuration, expose /health, /info and /metrics endpoints
management:
  endpoints:
    web:
      base-path: /
      exposure.include: health,info,metrics,prometheus
  endpoint.health.show-details: always
